Updates 5.4.45 container. Lets hope it works

diff --git a/php/5.4.45-apache/Dockerfile b/php/5.4.45-apache/Dockerfile
--- a/php/5.4.45-apache/Dockerfile
+++ b/php/5.4.45-apache/Dockerfile
@@ -1,82 +1,206 @@
+######
+# Base
+#####
 FROM debian:jessie
 
-# persistent / runtime deps
-RUN apt-get update && apt-get install -y ca-certificates curl librecode0 libsqlite3-0 libxml2 --no-install-recommends && rm -r /var/lib/apt/lists/*
+ENV DRUPALCI TRUE
 
-# phpize deps
-RUN apt-get update && apt-get install -y autoconf file g++ gcc libc-dev make pkg-config re2c gdb --no-install-recommends && rm -r /var/lib/apt/lists/*
-
-ENV PHP_INI_DIR /usr/local/etc/php
-RUN mkdir -p $PHP_INI_DIR/conf.d
-
-
+######
+# Apache Setup
+######
 RUN apt-get update && apt-get install -y apache2-bin apache2.2-common apache2-dbg --no-install-recommends && rm -rf /var/lib/apt/lists/*
 
-RUN rm -rf /var/www/html && mkdir -p /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html && chown -R www-data:www-data /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html
+RUN set -ex \
+	\
+	&& sed -ri 's/^export ([^=]+)=(.*)$/: ${\1:=\2}\nexport \1/' /etc/apache2/envvars \
+	\
+	&& . /etc/apache2/envvars \
+	&& for dir in \
+		"$APACHE_LOCK_DIR" \
+		"$APACHE_RUN_DIR" \
+		"$APACHE_LOG_DIR" \
+		/var/www/html \
+	; do \
+		rm -rvf "$dir" \
+		&& mkdir -p "$dir" \
+		&& chown -R "$APACHE_RUN_USER:$APACHE_RUN_GROUP" "$dir"; \
+	done
 
 # Apache + PHP requires preforking Apache for best results
 RUN a2dismod mpm_event && a2enmod mpm_prefork
 
-RUN mv /etc/apache2/apache2.conf /etc/apache2/apache2.conf.dist && rm /etc/apache2/conf-enabled/* /etc/apache2/sites-enabled/*
-COPY apache2.conf /etc/apache2/apache2.conf
-# it'd be nice if we could not COPY apache2.conf until the end of the Dockerfile, but its contents are checked by PHP during compilation
+# PHP files should be handled by PHP, and should be preferred over any other file type
+RUN { \
+		echo '<FilesMatch \.php$>'; \
+		echo '\tSetHandler application/x-httpd-php'; \
+		echo '</FilesMatch>'; \
+		echo; \
+		echo 'DirectoryIndex disabled'; \
+		echo 'DirectoryIndex index.php index.html'; \
+		echo; \
+		echo '<Directory /var/www/>'; \
+		echo '\tOptions -Indexes'; \
+		echo '\tAllowOverride All'; \
+		echo '</Directory>'; \
+	} | tee /etc/apache2/conf-available/docker-php.conf \
+	&& a2enconf docker-php
 
-ENV PHP_EXTRA_BUILD_DEPS apache2-dev
-ENV PHP_EXTRA_CONFIGURE_ARGS --with-apxs2
+COPY ./conf/apache2/vhost.conf /etc/apache2/sites-available/drupal.conf
+
+RUN a2enmod rewrite \
+    && a2dissite 000-default.conf \
+    && a2ensite drupal
+######
+# Php Setup
+######
+RUN apt-get update && apt-get install -y --no-install-recommends \
+        autoconf \
+		ca-certificates \
+		curl \
+		file \
+		g++ \
+		gcc \
+		gdb \
+		libc-dev \
+		libedit2 \
+		librecode0 \
+        libsqlite3-0 \
+		libxml2 \
+		make \
+		pkg-config \
+		re2c \
+		xz-utils \
+		&& rm -rf /var/lib/apt/lists/*
+
+RUN mkdir -p /usr/local/etc/php/conf.d
 
 
-ENV GPG_KEYS F38252826ACD957EF380D39F2F7956BC5DA04B5D
-RUN set -xe \
-	&& for key in $GPG_KEYS; do \
-		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
-	done
+
 
 ENV PHP_VERSION 5.4.45
+ENV PHP_URL="https://php.net/get/php-5.4.45.tar.gz/from/this/mirror"
 
-# --enable-mysqlnd is included below because it's harder to compile after the fact the extensions are (since it's a plugin for several extensions, not an extension in itself)
-RUN buildDeps=" \
-		$PHP_EXTRA_BUILD_DEPS \
+RUN set -xe; \
+	\
+	fetchDeps=' \
+		wget \
+	'; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends $fetchDeps; \
+	rm -rf /var/lib/apt/lists/*; \
+	\
+	mkdir -p /usr/src; \
+	cd /usr/src; \
+	\
+	wget -O php.tar.gz "$PHP_URL"; \
+	\
+	apt-get purge -y --auto-remove $fetchDeps
+
+COPY docker-php-source /usr/local/bin/
+
+RUN set -xe \
+    	&& buildDeps=" \
+        apache2-dev \
+        libcurl4-openssl-dev \
+        libedit-dev \
+        libfreetype6-dev \
+        libicu-dev \
+        libjpeg62-turbo-dev \
+        libmcrypt-dev \
+        libpng12-dev \
+        libpq-dev \
+        libsqlite3-dev \
+        libssl-dev \
+        libtidy-dev \
+        libxml2-dev \
+        libxslt1-dev \
+        libyaml-dev \
+        ncurses-dev \
 		bzip2 \
-		libcurl4-openssl-dev \
 		libreadline6-dev \
 		librecode-dev \
-		libsqlite3-dev \
-		libssl-dev \
-		libxml2-dev \
 	" \
-	&& set -x \
 	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
-	&& curl -SL "http://php.net/get/php-$PHP_VERSION.tar.bz2/from/this/mirror" -o php.tar.bz2 \
-	&& curl -SL "http://php.net/get/php-$PHP_VERSION.tar.bz2.asc/from/this/mirror" -o php.tar.bz2.asc \
-	&& gpg --verify php.tar.bz2.asc \
-	&& mkdir -p /usr/src/php \
-	&& tar -xof php.tar.bz2 -C /usr/src/php --strip-components=1 \
-	&& rm php.tar.bz2* \
-	&& cd /usr/src/php \
-	&& ./configure \
-		--with-config-file-path="$PHP_INI_DIR" \
-		--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
-		$PHP_EXTRA_CONFIGURE_ARGS \
-		--disable-cgi \
-		--enable-mysqlnd \
-		--with-curl \
-		--with-openssl \
-		--with-readline \
-		--with-recode \
-		--with-zlib \
-		--enable-debug \
-	&& make -j"$(nproc)" \
-	&& make install \
-	&& { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
-	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps \
-	&& make clean
+    	\
+    	&& docker-php-source extract \
+    	&& cd /usr/src/php \
+    	&& export CFLAGS="-O2 -g" \
+    		CPPFLAGS="-O2 -g" \
+    		LDFLAGS="" \
+    	&& ./configure \
+        		--with-config-file-path=/usr/local/etc/php \
+        		--with-config-file-scan-dir=/usr/local/etc/php/conf.d \
+        		--enable-ftp \
+        		--enable-mbstring \
+        		--enable-mysqlnd \
+        		--with-curl \
+        		--with-libedit \
+        		--with-openssl \
+        		--with-zlib \
+        		--with-kerberos \
+                --with-openssl \
+                --with-mysql=mysqlnd \
+                --with-mysqli=mysqlnd \
+                --with-pdo-mysql=mysqlnd \
+                --with-pdo-sqlite \
+                --with-pdo-pgsql \
+                --with-readline \
+                --with-recode \
+                --with-png-dir \
+                --with-freetype-dir \
+                --with-zlib-dir \
+                --with-jpeg-dir \
+                --with-mcrypt \
+                --with-xsl \
+                --with-tidy \
+                --with-xmlrpc \
+                --with-gettext=shared \
+        		--with-gd \
+                --with-pear \
+                --enable-sockets \
+                --enable-exif \
+                --enable-zip \
+                --enable-soap \
+                --enable-sysvsem \
+                --enable-cgi \
+                --enable-sysvshm \
+                --enable-shmop \
+                --enable-pcntl \
+                --enable-bcmath \
+                --enable-xmlreader \
+                --enable-intl \
+                --enable-wddx \
+                --enable-opcache \
+        		--with-apxs2 \
+        	&& make -j "$(nproc)" \
+        	&& make install \
+        	&& { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
+        	&& make clean
 
-COPY docker-php-ext-* /usr/local/bin/
+COPY docker-php-ext-* docker-php-entrypoint /usr/local/bin/
 
+# install pecl extensions for apcu, xdebug, and yaml
+RUN docker-php-ext-pecl-install APC-3.1.13 xdebug-2.4.1 \
+    && sed -i 's/^/;/' /usr/local/etc/php/conf.d/docker-php-pecl-xdebug.ini \
+    && apt-get update \
+    && apt-get install -y mysql-client postgresql-client sudo sqlite3 --no-install-recommends \
+    && rm -rf /var/lib/apt/lists/*
+
+COPY ./conf/php/php.ini /usr/local/etc/php/php.ini
+COPY ./conf/php/php-cli.ini /usr/local/etc/php/php-cli.ini
+
+# Install Composer, Drush
+RUN curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
+  && curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
+  && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }" \
+  && curl -o /usr/local/bin/drush http://files.drush.org/drush.phar \
+  && chmod +x /usr/local/bin/drush \
+  && /usr/local/bin/drush --version
+
+ENTRYPOINT ["docker-php-entrypoint"]
 
 COPY apache2-foreground /usr/local/bin/
 WORKDIR /var/www/html
 
 EXPOSE 80
 CMD ["apache2-foreground"]
-
